### ISSUE TITLE
Bigger text

### ISSUE THREAD

**Issue by agrofx1** [SomethingWithComputers/pixoo#21]
Hello. It is possible to set text size? I don't find how in examples.py.

**Comment by SomethingWithComputers** [comment]
Hey there! The thing is, we're using a digitized pixel font (namely the PICO-8 font). But it's relatively easy to make a different version if you want it. There are other (free) pixel fonts, that are slightly larger, that'd be the easiest. Upscaling it some other way is kinda difficult, because they're basically just tiny matrixes of which pixels go where.

**Comment by agrofx1** [comment]
Hi! Thanks for answering. I will change the font locally.
